### ISSUE TITLE
Do test build as part of CI run

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-ckeditor#111]
Current master is choking during `ck.sh build` on modern JS syntax introduced in https://github.com/liferay/liferay-ckeditor/pull/102:

```
Copying files (relax, this may take a while)
Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: plugin.js:121: WARNING - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
                        },
                         ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:34: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        afterInit(editor) {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:44: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        getToolbarsWidth() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:58: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        isToolbarOverflowing() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:78: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        onInstanceReady(event) {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: plugin.js:114: ERROR - this language feature is only supported in es6 mode: member declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
                        onLoad() {
                        ^

Aug 06, 2020 6:09:52 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 5 error(s), 1 warning(s)
Exception in thread "main" org.mozilla.javascript.JavaScriptException: Unable to compile file: /Users/greghurrell/code/liferay-ckeditor/ckeditor-dev/dev/builder/release/ckeditor/plugins/toolbarwatcher/plugin.js (C:\ckbuilder\src/lib/javascript.js#68)
        at ckbuilder.lib.javascript._c_compileFile_2(C:\ckbuilder\src/lib/javascript.js:68)
        at ckbuilder.lib.javascript.call(C:\ckbuilder\src/lib/javascript.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at ckbuilder.lib.javascript._c_anonymous_5(C:\ckbuilder\src/lib/javascript.js:167)
        at ckbuilder.lib.javascript.call(C:\ckbuilder\src/lib/javascript.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.lib.builder._c_anonymous_14(C:\ckbuilder\src/lib/builder.js:454)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:285)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.io._c_anonymous_9(C:\ckbuilder\src/lib/io.js:299)
        at ckbuilder.lib.io.call(C:\ckbuilder\src/lib/io.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.builder._c_copyFiles_12(C:\ckbuilder\src/lib/builder.js:376)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at ckbuilder.lib.builder._c_anonymous_20(C:\ckbuilder\src/lib/builder.js:691)
        at ckbuilder.lib.builder.call(C:\ckbuilder\src/lib/builder.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
        at ckbuilder.lib.controller._c_anonymous_5(C:\ckbuilder\src/lib/controller.js:78)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at ckbuilder.lib.controller._c_anonymous_14(C:\ckbuilder\src/lib/controller.js:235)
        at ckbuilder.lib.controller.call(C:\ckbuilder\src/lib/controller.js)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at ckbuilder.ckbuilder._c_script_0(C:\ckbuilder\src/ckbuilder.js:112)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at ckbuilder.ckbuilder.call(C:\ckbuilder\src/ckbuilder.js)
        at ckbuilder.ckbuilder.exec(C:\ckbuilder\src/ckbuilder.js)
        at org.mozilla.javascript.optimizer.OptRuntime$1.run(OptRuntime.java:218)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.optimizer.OptRuntime.main(OptRuntime.java:206)
        at ckbuilder.ckbuilder.main(C:\ckbuilder\src/ckbuilder.js)
^C\n\nAborting.\n
```

Our CI check is super-lightweight, just checking formatting and that [the submodule is legit](https://github.com/liferay/liferay-ckeditor/blob/a85622bf54109df259c89a1af625dff05a08f1da/support/checkSubmodule.js), but evidently it should do more to catch this kind of problem. (I think we always just assumed that the person committing the changes would do a build to verify, and so we could afford to avoid the heavyweight build process, but that's obviously not a good idea.)
